<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>{{PROJECT_NAME}}.DesktopApp</AssemblyName>
    <RootNamespace>{{PROJECT_NAME}}.DesktopApp</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\{{PROJECT_NAME}}.Core\{{PROJECT_NAME}}.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>
</Project>
